# vim: ts=2 sw=2 et
name: Test and merge on push

on:
  push:
    branches:
    - dev
  pull_request:
    types:
    - synchronize
    branches:
    - dev

jobs:
  test:
    uses: ./.github/workflows/test.yaml
    if: ${{ github.event.action != 'synchronize' }}

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: |
        needs.test.result == 'success' ||
        needs.test.result == 'skipped'
    steps:
    - name: Merge into main
      run: |
        set -x
        cred=${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}
        repo=https://${cred}@github.com/${{ github.repository }}.git
        git clone ${repo}
        git remote set-url origin ${repo}
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git merge origin/dev --no-ff -m "Auto-merge dev into main."
        git push
