# vim: ts=2 sw=2 et
name: Test and merge on push

on:
  push:
    branches:
    - dev
  pull_request:
    types:
    - synchronize
    branches:
    - dev

jobs:
  test:
    name: Test unless merging PR
    uses: ./.github/workflows/test.yaml
    if: ${{ github.event.action != 'synchronize' }}
    
  merge:
    runs-on: ubuntu-latest
    needs: test
    if: |
      (
        needs.test.result == 'success' || 
        needs.test == 'skipped'
      ) &&
      github.event.action == 'push' &&
      github.event.head_ref == 'refs/heads/dev'
    steps:
    - name: Check-out dev
      uses: actions/checkout@v4
    - name: Merge into main
      run: |
        git checkout main
        git merge dev --no-ff -m 'Auto-merge dev into main.'
        git push origin main
