# vim: ts=2 sw=2 et
name: Test and merge on push

on:
  push:
    branches:
    - dev
  pull_request:
    types:
    - synchronize
    branches:
    - dev

jobs:
  test:
    uses: ./.github/workflows/test.yaml
    if: ${{ github.event.action != 'synchronize' }}

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: |
        needs.test.result == 'success' ||
        needs.test.result == 'skipped'
    steps:
    - name: Check-out dev
      uses: actions/checkout@v4
    - name: Set committer identity
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    - name: Merge into main
      run: |
        set -x
        ls -lha
        git fetch --all
        git status
        git switch main
        git branch -vva
        git remote -v
        git status
        git log main..dev
        git merge dev --no-ff -m 'Auto-merge dev into main.'
        git push origin main
