# vim: ts=2 sw=2 et
name: Auto-merge

on:
  push:
    branches:
    - dev
  pull_request:
    types:
    - synchronize
    branches:
    - dev

jobs:
  test-and-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Check-out code
    - uses: actions/checkout@v4
    - name: Test unless merging PR
      uses: .github/workflows/test.yaml
      if: ${{ github.event.action != 'synchronize' }}
    - name: Merge into main
      if: |
          github.event.action == 'push' &&
          github.event.head_ref == 'refs/heads/dev'
      run: |
        git checkout main
        git merge dev --no-ff -m 'Auto-merge dev into main.'
        git push origin main
