# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  alpine:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
      volumes:
      - /sys/fs/cgroup
    steps:
    - name: Check-out repository
      uses: actions/checkout@v4
    - name: Install OpenRC
      run: apk add openrc
    - name: Start OpenRC
      run: mkdir -p /run/openrc/softlevel && openrc default
    - name: Test bootstrapping
      run: sh -x bootstrap

  fedora:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
      volumes:
      - /sys/fs/cgroup
    steps:
    - name: Check-out repository
      uses: actions/checkout@v4
    - name: Test bootstrapping
      run: sh -x bootstrap
