# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  alpine:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
    - name: Check-out repository
      uses: actions/checkout@v4
    - name: Explore environment
      run: |
        pwd -P
        whoami
        echo $0
        date
        env
    - name: Test bootstrapping
      run: sh bootstrap
