# Test bootstrap script on a few platforms.
name: Test on pull request

# Permit call from another workflow with `workflow_call` and manual runs with
# `workflow_dispatch`.
on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches:
    - dev

jobs:

  alpine:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
      volumes:
      - /sys/fs/cgroup
    steps:
    - name: Check-out repository
      uses: actions/checkout@v4
    - name: Install OpenRC
      run: apk add openrc
    - name: Start OpenRC
      run: mkdir -p /run/openrc/softlevel && openrc default
    - name: Test bootstrapping
      run: sh -x bootstrap

  # Restrict default 6 GB of RAM. Files at same path inside the VM as outside.
  # Do not copy unneeded files back; we override the root SSH keys.
  openbsd:
    runs-on: ubuntu-latest
    steps:
    - name: Check-out repository
      uses: actions/checkout@v4
    - name: Test in OpenBSD
      uses: vmactions/openbsd-vm@v1
      with:
        mem: 4096
        copyback: false
        run: sh -x ${{ github.workspace }}/bootstrap
          
  # Module `container` had user permission issues.
  termux:
    runs-on: ubuntu-latest
    steps:
    - name: Check-out repository
      uses: actions/checkout@v4
    - name: Remove Android components
      run:  sed -i '/termux-wake-lock/d' bootstrap
    - name: Test bootstrapping
      run: |
        docker run \
          -v ${{ github.workspace }}:/mnt \
          termux/termux-docker:latest sh -x /mnt/bootstrap

  # Must use PID 1 for systemd in container.
  fedora:
    runs-on: ubuntu-latest
    steps:
    - name: Check-out repository
      uses: actions/checkout@v4
    - name: Create Dockerfile
      run: |
        echo '
          FROM fedora:latest
          RUN dnf -y update && dnf install -y iproute systemd
          COPY . /mnt
          WORKDIR /mnt
          ENTRYPOINT ["/sbin/init"]
        ' >Dockerfile
    - name: Build Docker image
      run: docker build -t fedora-image .
    - name: Launch systemd
      run: |
        docker run \
          -d \
          --privileged=true \
          --name Mickey \
          fedora-image
    - name: Wait for systemd
      run: timeout 30 sh -c '
          until docker exec Mickey systemctl is-system-running; do
            sleep 3; 
          done
        '
    - name: Test bootstrapping
      run: docker exec Mickey sh -x bootstrap
