---
name: Test environment setup

"on":
  workflow_dispatch: {}
  pull_request: {}
  push:
    paths:
      - setup.sh

jobs:
  setup:
    name: Set up environment
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v4
      - name: Run setup script
        run: sh -x setup.sh
